---

- name: Download & unarchive aws-cli executable
  become: true
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: ~/
    remote_src: yes

- name: Install aws-cli
  become: true
  shell: ~/aws/install --update

- name: Clean install folder
  become: true
  file:
    path: ~/aws
    state: absent