---

- name: Download Docker convenience script
  become: true
  get_url:
    url: https://get.docker.com
    dest: ~/get-docker.sh
    mode: '0777'

- name: Install Docker
  become: true
  shell: ~/get-docker.sh --update

- name: Remove install script
  become: true
  file:
    path: ~/get-docker.sh
    state: absent